version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres-container
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: DOCKER_FCCPD
      POSTGRES_DB: apiFCCPD
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://docker:DOCKER_FCCPD@postgres:5432/apiFCCPD
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
